<a href="https://colab.research.google.com/github/chmawnt/Complete-Feature-Selection/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#Create a null vector of size 10
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#Create a vector with values ranging from 10 to 49


In [3]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Find the shape of previous array in question 3

In [5]:
arr = np.array([10,11, 12 ,13, 14 ,15, 16, 17, 18 ,19, 20, 21 ,22, 23, 24, 25, 26 ,27 ,28, 29 ,30 ,31, 32, 33,
 34 ,35, 36, 37, 38, 39 ,40, 41, 42, 43, 44, 45 ,46, 47, 48])
print(arr.shape)

(39,)


Print the type of the previous array in question 3


In [7]:
arr.dtype

dtype('int64')

Print the numpy version and the configuration

In [9]:
print(np.__version__)
print(np.show_config)

1.19.5
<function show at 0x7ff413fa5ef0>


Print the dimension of the array in question 3
Create a boolean array with all the True values

In [12]:
print(v.ndim)
ans = np.full((2,2),True,dtype=bool)
print(ans)

1
[[ True  True]
 [ True  True]]


Create a two dimensional array

In [14]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x.shape) 

(2, 4)


In [ ]:

Difficulty Level Easy

Reverse a vector (first element becomes last)
In [ ]:

Create a null vector of size 10 but the fifth value which is 1

Create a 3x3 identity matrix
In [ ]:

arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [ ]:

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply arr1 with arr2

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [ ]:

Extract all odd numbers from arr with values(0-9)
In [ ]:

Replace all odd numbers to -1 from previous array
In [ ]:

arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

Create a 2d array with 1 on the border and 0 inside
In [ ]:

Difficulty Level Medium

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [ ]:

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [ ]:

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
In [ ]:

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
In [ ]:

Create a 10x10 array with random values and find the minimum and maximum values
In [ ]:

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [ ]:

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the positions where elements of a and b match

In [ ]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [ ]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [ ]:

Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
In [ ]:
Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
In [ ]:

Swap axes of the array you created in Question 32
In [ ]:

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
In [ ]:

Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
In [ ]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [ ]:

a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b
Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [ ]:

x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [ ]:

Generate a matrix of 20 random values and find its cumulative sum

Create a three dimensional array

In [15]:
D3 = np.zeros((3,3,4))
print(D3)
print(D3.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 3, 4)


Reverse a vector (first element becomes last)

In [19]:
rev=np.array([1,2,3,4,5,6,7,8,9,10])
print("Sort Array",rev)
rev=rev[::-1]
print("Reverse Array",rev)

Sort Array [ 1  2  3  4  5  6  7  8  9 10]
Reverse Array [10  9  8  7  6  5  4  3  2  1]
